function modelOffData = importmodelOff_aoa0(workbookFile, sheetName, dataLines)
%IMPORTFILE1 Import data from a spreadsheet
%  MODELOFFDATA = IMPORTFILE1(FILE) reads data from the first worksheet
%  in the Microsoft Excel spreadsheet file named FILE.  Returns the data
%  as a table.
%
%  MODELOFFDATA = IMPORTFILE1(FILE, SHEET) reads from the specified
%  worksheet.
%
%  MODELOFFDATA = IMPORTFILE1(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  modelOffData = importfile1("D:\TUD\Courses\Experimental Simulation\modelOffData.xlsx", "Sheet1", [12, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 01-Apr-2026 14:21:45

%% Input handling

% If no sheet is specified, read from Sheet1
if nargin == 1 || isempty(sheetName)
    sheetName = "Sheet1";
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [12, Inf];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 17);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = dataLines(1, :);

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "AoA", "AoS", "CD1", "Cy1", "CL1", "CMroll1", "CMpitch1", "CMyaw1"];
opts.SelectedVariableNames = ["AoA", "AoS", "CD1", "Cy1", "CL1", "CMroll1", "CMpitch1", "CMyaw1"];
opts.VariableTypes = ["char", "char", "char", "char", "char", "char", "char", "char", "char", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9"], "EmptyFieldRule", "auto");

% Import the data
modelOffData    = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = dataLines(idx, :);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    modelOffData = [modelOffData; tb]; %#ok<AGROW>
end

modelOffData.V  = 40 * ones(height(modelOffData),1);

end