function modelOffData = importmodelOff_aos0(workbookFile, sheetName, dataLines)
%IMPORTFILE1 Import data from a spreadsheet
%  MODELOFFDATA = IMPORTFILE1(FILE) reads data from the first worksheet
%  in the Microsoft Excel spreadsheet file named FILE.  Returns the data
%  as a table.
%
%  MODELOFFDATA = IMPORTFILE1(FILE, SHEET) reads from the specified
%  worksheet.
%
%  MODELOFFDATA = IMPORTFILE1(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  modelOffData = importfile1("D:\TUD\Courses\Experimental Simulation\modelOffData.xlsx", "Sheet1", [12, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 01-Apr-2026 14:15:26

%% Input handling

% If no sheet is specified, read from Sheet1
if nargin == 1 || isempty(sheetName)
    sheetName = "Sheet1";
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [12, Inf];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 8);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = dataLines(1, :);

% Specify column names and types
opts.VariableNames = ["AoA", "AoS", "CD", "Cy", "CL", "CMroll", "CMpitch", "CMyaw"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double"];

% Import the data
modelOffData = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = dataLines(idx, :);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    modelOffData = [modelOffData; tb]; %#ok<AGROW>
end

modelOffData.V  = 40 * ones(height(modelOffData),1);
end